# Generated by Django 2.2.1 on 2020-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.TextField()),
                ('email', models.EmailField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('contact', models.IntegerField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
