# Generated by Django 2.2.1 on 2020-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200416_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
