# Generated by Django 2.2.1 on 2020-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_comp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
