# Generated by Django 2.2.1 on 2020-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200417_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_comp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
